[build]
  publish = "."

[[headers]]
  for = "/app.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/sites.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
